// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePassword(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<string>;

export function Greet(arg1:string):Promise<string>;
